// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mgr_1_2_TI.DAL;

#nullable disable

namespace mgr_1_2_TI.Migrations
{
    [DbContext(typeof(MovieContext))]
    [Migration("20260408062840_migr_20260408_082833")]
    partial class migr_20260408_082833
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("mgr_1_2_TI.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("T_Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Fast-paced movies with intense physical action, stunts, and battles.",
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Light-hearted films designed to make the audience laugh.",
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Serious films focusing on realistic characters and emotional themes.",
                            Name = "Drama"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Movies exploring futuristic concepts, advanced technology, and space exploration.",
                            Name = "Sci-Fi"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Films intended to frighten, shock, or suspense the audience.",
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Stories centered on passionate, emotional, and romantic involvement.",
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Suspenseful movies with tension, excitement, and a sense of danger.",
                            Name = "Thriller"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Films created using animation techniques, often aimed at children and families.",
                            Name = "Animation"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Non-fictional films intended to document reality, primarily for instruction or maintaining a historical record.",
                            Name = "Documentary"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Movies set in imaginary worlds, often involving magic, mythical creatures, and supernatural events.",
                            Name = "Fantasy"
                        });
                });

            modelBuilder.Entity("mgr_1_2_TI.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Director")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PosterName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("T_Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "A superhero film about Batman facing the Joker in Gotham City.",
                            Director = "Christopher Nolan",
                            PosterName = "1.png",
                            Price = 19.99m,
                            Title = "The Dark Knight"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland with the aid of a group of female prisoners, a psychotic worshiper, and a drifter named Max.",
                            Director = "George Miller",
                            PosterName = "2.png",
                            Price = 18.99m,
                            Title = "Mad Max: Fury Road"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "An ex-hit-man comes out of retirement to track down the gangsters that killed his dog and took everything from him.",
                            Director = "Chad Stahelski",
                            PosterName = "3.png",
                            Price = 17.99m,
                            Title = "John Wick"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "An NYPD officer tries to save his wife and several others taken hostage by German terrorists during a Christmas party at the Nakatomi Plaza in Los Angeles.",
                            Director = "John McTiernan",
                            PosterName = "4.png",
                            Price = 16.99m,
                            Title = "Die Hard"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "Earth's mightiest heroes must come together and learn to fight as a team if they are going to stop the mischievous Loki and his alien army from enslaving humanity.",
                            Director = "Joss Whedon",
                            PosterName = "5.png",
                            Price = 21.99m,
                            Title = "The Avengers"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Description = "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.",
                            Director = "Ridley Scott",
                            PosterName = "6.png",
                            Price = 20.99m,
                            Title = "Gladiator"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Description = "Ethan Hunt and his IMF team, along with some familiar allies, race against time after a mission gone wrong.",
                            Director = "Christopher McQuarrie",
                            PosterName = "7.png",
                            Price = 22.99m,
                            Title = "Mission: Impossible - Fallout"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Description = "A man is picked up by a fishing boat, bullet-riddled and suffering from amnesia, before racing to elude assassins and regain his memory.",
                            Director = "Doug Liman",
                            PosterName = "8.png",
                            Price = 15.99m,
                            Title = "The Bourne Identity"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            Description = "A young police officer must prevent a bomb exploding aboard a city bus by keeping its speed above 50 mph.",
                            Director = "Jan de Bont",
                            PosterName = "9.png",
                            Price = 14.99m,
                            Title = "Speed"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            Description = "A human soldier is sent from 2029 to 1984 to stop an almost indestructible cyborg killing machine, sent from the same year, which has been programmed to execute a young woman whose unborn son is the key to humanity's future salvation.",
                            Director = "James Cameron",
                            PosterName = "10.png",
                            Price = 13.99m,
                            Title = "The Terminator"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            Description = "After earning 00 status and a licence to kill, Secret Agent James Bond sets out on his first mission as 007. Bond must defeat a private banker funding terrorists in a high-stakes game of poker at Casino Royale, Montenegro.",
                            Director = "Martin Campbell",
                            PosterName = "11.png",
                            Price = 19.99m,
                            Title = "Casino Royale"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 1,
                            Description = "A S.W.A.T. team becomes trapped in a tenement run by a ruthless mobster and his army of killers and thugs.",
                            Director = "Gareth Evans",
                            PosterName = "12.png",
                            Price = 16.99m,
                            Title = "The Raid"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            Description = "Two co-dependent high school seniors are forced to deal with separation anxiety after their plan to stage a booze-soaked party goes awry.",
                            Director = "Greg Mottola",
                            PosterName = "13.png",
                            Price = 9.99m,
                            Title = "Superbad"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            Description = "Three buddies wake up from a bachelor party in Las Vegas, with no memory of the previous night and the bachelor missing.",
                            Director = "Todd Phillips",
                            PosterName = "14.png",
                            Price = 11.99m,
                            Title = "The Hangover"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            Description = "Competition between the maid of honor and a bridesmaid, over who is the bride's best friend, threatens to upend the life of an out-of-work pastry chef.",
                            Director = "Paul Feig",
                            PosterName = "15.png",
                            Price = 10.99m,
                            Title = "Bridesmaids"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            Description = "Two aimless middle-aged losers still living at home are forced against their will to become roommates when their parents marry.",
                            Director = "Adam McKay",
                            PosterName = "16.png",
                            Price = 12.99m,
                            Title = "Step Brothers"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            Description = "Ron Burgundy is San Diego's top-rated newsman in the male-dominated broadcasting of the 1970s, but that's all about to change for Ron and his cronies when an ambitious woman shows up.",
                            Director = "Adam McKay",
                            PosterName = "17.png",
                            Price = 13.99m,
                            Title = "Anchorman: The Legend of Ron Burgundy"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 2,
                            Description = "The cross-country adventures of two good-hearted but incredibly stupid friends.",
                            Director = "Peter Farrelly",
                            PosterName = "18.png",
                            Price = 14.99m,
                            Title = "Dumb and Dumber"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 2,
                            Description = "Goaded by his buddies, a nerdy guy who's never 'done the deed' only finds the pressure mounting when he meets a single mother.",
                            Director = "Judd Apatow",
                            PosterName = "19.png",
                            Price = 15.99m,
                            Title = "The 40-Year-Old Virgin"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 2,
                            Description = "At the end of his career, a clueless fashion model is brainwashed to kill the Prime Minister of Malaysia.",
                            Director = "Ben Stiller",
                            PosterName = "20.png",
                            Price = 16.99m,
                            Title = "Zoolander"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 2,
                            Description = "Three friends attempt to recapture their glory days by opening up a fraternity near their old alma mater.",
                            Director = "Todd Phillips",
                            PosterName = "21.png",
                            Price = 17.99m,
                            Title = "Old School"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 2,
                            Description = "A man afraid to fly must ensure that a plane lands safely after the pilots become sick.",
                            Director = "Jim Abrahams",
                            PosterName = "22.png",
                            Price = 18.99m,
                            Title = "Airplane!"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 2,
                            Description = "Two mismatched New York City detectives seize an opportunity to step up like the city's top cops, whom they idolize, only things don't quite go as planned.",
                            Director = "Adam McKay",
                            PosterName = "23.png",
                            Price = 19.99m,
                            Title = "The Other Guys"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 2,
                            Description = "Through a series of freak occurrences, a group of actors shooting a big-budget war movie are forced to become the soldiers they are portraying.",
                            Director = "Ben Stiller",
                            PosterName = "24.png",
                            Price = 20.99m,
                            Title = "Tropic Thunder"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 3,
                            Description = "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
                            Director = "Frank Darabont",
                            PosterName = "25.png",
                            Price = 14.99m,
                            Title = "The Shawshank Redemption"
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 3,
                            Description = "The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75.",
                            Director = "Robert Zemeckis",
                            PosterName = "26.png",
                            Price = 13.99m,
                            Title = "Forrest Gump"
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 3,
                            Description = "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
                            Director = "Francis Ford Coppola",
                            PosterName = "27.png",
                            Price = 19.99m,
                            Title = "The Godfather"
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 3,
                            Description = "In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.",
                            Director = "Steven Spielberg",
                            PosterName = "28.png",
                            Price = 18.99m,
                            Title = "Schindler's List"
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 3,
                            Description = "A struggling salesman takes custody of his son as he's poised to begin a life-changing professional career.",
                            Director = "Gabriele Muccino",
                            PosterName = "29.png",
                            Price = 17.99m,
                            Title = "The Pursuit of Happyness"
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 3,
                            Description = "Will Hunting, a janitor at M.I.T., has a gift for mathematics, but needs help from a psychologist to find direction in his life.",
                            Director = "Gus Van Sant",
                            PosterName = "30.png",
                            Price = 16.99m,
                            Title = "Good Will Hunting"
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 3,
                            Description = "After John Nash, a brilliant but asocial mathematician, accepts secret work in cryptography, his life takes a turn for the nightmarish.",
                            Director = "Ron Howard",
                            PosterName = "31.png",
                            Price = 15.99m,
                            Title = "A Beautiful Mind"
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 3,
                            Description = "Harvard student Mark Zuckerberg creates the social networking site that would become known as Facebook, but is later sued by two brothers who claimed he stole their idea.",
                            Director = "David Fincher",
                            PosterName = "32.png",
                            Price = 16.99m,
                            Title = "The Social Network"
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 3,
                            Description = "Selfish yuppie Charlie Babbitt's father left a fortune to his savant brother Raymond and a pittance to Charlie; they travel cross-country.",
                            Director = "Barry Levinson",
                            PosterName = "33.png",
                            Price = 14.99m,
                            Title = "Rain Man"
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 3,
                            Description = "The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape but who has a mysterious gift.",
                            Director = "Frank Darabont",
                            PosterName = "34.png",
                            Price = 13.99m,
                            Title = "The Green Mile"
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 3,
                            Description = "A Polish Jewish musician struggles to survive the destruction of the Warsaw ghetto of World War II.",
                            Director = "Roman Polanski",
                            PosterName = "35.png",
                            Price = 12.99m,
                            Title = "The Pianist"
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 3,
                            Description = "A jury holdout attempts to prevent a miscarriage of justice by forcing his colleagues to reconsider the evidence.",
                            Director = "Sidney Lumet",
                            PosterName = "36.png",
                            Price = 11.99m,
                            Title = "12 Angry Men"
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 4,
                            Description = "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
                            Director = "Christopher Nolan",
                            PosterName = "37.png",
                            Price = 22.99m,
                            Title = "Inception"
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 4,
                            Description = "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
                            Director = "Lana Wachowski",
                            PosterName = "38.png",
                            Price = 20.99m,
                            Title = "The Matrix"
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 4,
                            Description = "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
                            Director = "Christopher Nolan",
                            PosterName = "39.png",
                            Price = 21.99m,
                            Title = "Interstellar"
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 4,
                            Description = "A young blade runner's discovery of a long-buried secret leads him to track down former blade runner Rick Deckard, who's been missing for thirty years.",
                            Director = "Denis Villeneuve",
                            PosterName = "40.png",
                            Price = 23.99m,
                            Title = "Blade Runner 2049"
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 4,
                            Description = "A linguist works with the military to communicate with alien lifeforms after twelve mysterious spacecraft appear around the world.",
                            Director = "Denis Villeneuve",
                            PosterName = "41.png",
                            Price = 22.99m,
                            Title = "Arrival"
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 4,
                            Description = "An astronaut becomes stranded on Mars after his team assume him dead, and must rely on his ingenuity to find a way to signal to Earth that he is alive.",
                            Director = "Ridley Scott",
                            PosterName = "42.png",
                            Price = 21.99m,
                            Title = "The Martian"
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 4,
                            Description = "A young programmer is selected to participate in a ground-breaking experiment in synthetic intelligence by evaluating the human qualities of a breathtaking female A.I.",
                            Director = "Alex Garland",
                            PosterName = "43.png",
                            Price = 20.99m,
                            Title = "Ex Machina"
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 4,
                            Description = "A noble family becomes entangled in a war for control over the galaxy's most valuable asset while its heir becomes troubled by visions of a dark future.",
                            Director = "Denis Villeneuve",
                            PosterName = "44.png",
                            Price = 24.99m,
                            Title = "Dune"
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 4,
                            Description = "Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee and two droids to save the galaxy from the Empire's world-destroying battle station, while also attempting to rescue Princess Leia from the mysterious Darth Vader.",
                            Director = "George Lucas",
                            PosterName = "45.png",
                            Price = 19.99m,
                            Title = "Star Wars: Episode IV - A New Hope"
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 4,
                            Description = "In the colorful future, a cab driver unwittingly becomes the central figure in the search for a legendary cosmic weapon to keep Evil and Mr. Zorg at bay.",
                            Director = "Luc Besson",
                            PosterName = "46.png",
                            Price = 18.99m,
                            Title = "The Fifth Element"
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 4,
                            Description = "A troubled child summons the courage to help a friendly alien escape Earth and return to his home world.",
                            Director = "Steven Spielberg",
                            PosterName = "47.png",
                            Price = 17.99m,
                            Title = "E.T. the Extra-Terrestrial"
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 4,
                            Description = "In a future where a special police unit is able to arrest murderers before they commit their crimes, an officer from that unit is himself accused of a future murder.",
                            Director = "Steven Spielberg",
                            PosterName = "48.png",
                            Price = 16.99m,
                            Title = "Minority Report"
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 5,
                            Description = "Paranormal investigators Ed and Lorraine Warren work to help a family terrorized by a dark presence in their farmhouse.",
                            Director = "James Wan",
                            PosterName = "49.png",
                            Price = 16.99m,
                            Title = "The Conjuring"
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 5,
                            Description = "A young African-American visits his white girlfriend's parents for the weekend, where his uneasiness about their reception of him eventually reaches a boiling point.",
                            Director = "Jordan Peele",
                            PosterName = "50.png",
                            Price = 17.99m,
                            Title = "Get Out"
                        },
                        new
                        {
                            Id = 51,
                            CategoryId = 5,
                            Description = "A grieving family is haunted by tragic and disturbing occurrences.",
                            Director = "Ari Aster",
                            PosterName = "51.png",
                            Price = 18.99m,
                            Title = "Hereditary"
                        },
                        new
                        {
                            Id = 52,
                            CategoryId = 5,
                            Description = "When a 12-year-old girl is possessed by a mysterious entity, her mother seeks the help of two priests to save her.",
                            Director = "William Friedkin",
                            PosterName = "52.png",
                            Price = 19.99m,
                            Title = "The Exorcist"
                        },
                        new
                        {
                            Id = 53,
                            CategoryId = 5,
                            Description = "In a post-apocalyptic world, a family is forced to live in silence while hiding from monsters with ultra-sensitive hearing.",
                            Director = "John Krasinski",
                            PosterName = "53.png",
                            Price = 20.99m,
                            Title = "A Quiet Place"
                        },
                        new
                        {
                            Id = 54,
                            CategoryId = 5,
                            Description = "A family heads to an isolated hotel for the winter where a sinister presence influences the father into violence, while his psychic son sees horrific forebodings from both past and future.",
                            Director = "Stanley Kubrick",
                            PosterName = "54.png",
                            Price = 21.99m,
                            Title = "The Shining"
                        },
                        new
                        {
                            Id = 55,
                            CategoryId = 5,
                            Description = "In the summer of 1989, a group of bullied kids band together to destroy a shapeshifting monster, which disguises itself as a clown and preys on the children of Derry, their small Maine town.",
                            Director = "Andy Muschietti",
                            PosterName = "55.png",
                            Price = 22.99m,
                            Title = "It"
                        },
                        new
                        {
                            Id = 56,
                            CategoryId = 5,
                            Description = "A journalist must investigate a mysterious videotape which seems to cause the death of anyone in a week of viewing it.",
                            Director = "Gore Verbinski",
                            PosterName = "56.png",
                            Price = 23.99m,
                            Title = "The Ring"
                        },
                        new
                        {
                            Id = 57,
                            CategoryId = 5,
                            Description = "After moving into a suburban home, a couple becomes increasingly disturbed by a nightly demonic presence.",
                            Director = "Oren Peli",
                            PosterName = "57.png",
                            Price = 24.99m,
                            Title = "Paranormal Activity"
                        },
                        new
                        {
                            Id = 58,
                            CategoryId = 5,
                            Description = "A single mother, plagued by the violent death of her husband, battles with her son's fear of a monster lurking in the house, but soon discovers a sinister presence all around her.",
                            Director = "Jennifer Kent",
                            PosterName = "58.png",
                            Price = 25.99m,
                            Title = "The Babadook"
                        },
                        new
                        {
                            Id = 59,
                            CategoryId = 5,
                            Description = "Found footage helps a true-crime novelist realize how and why a family was murdered in his new home, though his discoveries put his entire family in the path of a supernatural entity.",
                            Director = "Scott Derrickson",
                            PosterName = "59.png",
                            Price = 26.99m,
                            Title = "Sinister"
                        },
                        new
                        {
                            Id = 60,
                            CategoryId = 5,
                            Description = "A family looks to prevent evil spirits from trapping their comatose child in a realm called The Further.",
                            Director = "James Wan",
                            PosterName = "60.png",
                            Price = 27.99m,
                            Title = "Insidious"
                        },
                        new
                        {
                            Id = 61,
                            CategoryId = 6,
                            Description = "A jazz pianist falls for an aspiring actress in Los Angeles.",
                            Director = "Damien Chazelle",
                            PosterName = "61.png",
                            Price = 15.99m,
                            Title = "La La Land"
                        },
                        new
                        {
                            Id = 62,
                            CategoryId = 6,
                            Description = "A poor yet passionate young man falls in love with a rich young woman, giving her a sense of freedom, but they are soon separated because of their social differences.",
                            Director = "Nick Cassavetes",
                            PosterName = "62.png",
                            Price = 14.99m,
                            Title = "The Notebook"
                        },
                        new
                        {
                            Id = 63,
                            CategoryId = 6,
                            Description = "A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.",
                            Director = "James Cameron",
                            PosterName = "63.png",
                            Price = 13.99m,
                            Title = "Titanic"
                        },
                        new
                        {
                            Id = 64,
                            CategoryId = 6,
                            Description = "Sparks fly when spirited Elizabeth Bennet meets single, rich, and proud Mr. Darcy. But Mr. Darcy reluctantly finds himself falling in love with a woman beneath his class.",
                            Director = "Joe Wright",
                            PosterName = "64.png",
                            Price = 12.99m,
                            Title = "Pride & Prejudice"
                        },
                        new
                        {
                            Id = 65,
                            CategoryId = 6,
                            Description = "A young man and woman meet on a train in Europe, and wind up spending one evening together in Vienna. Unfortunately, both know that this will probably be their only night together.",
                            Director = "Richard Linklater",
                            PosterName = "65.png",
                            Price = 11.99m,
                            Title = "Before Sunrise"
                        },
                        new
                        {
                            Id = 66,
                            CategoryId = 6,
                            Description = "A middle-aged husband's life changes dramatically when his wife asks him for a divorce. He seeks to rediscover his manhood with the help of a newfound friend.",
                            Director = "Glenn Ficarra",
                            PosterName = "66.png",
                            Price = 10.99m,
                            Title = "Crazy, Stupid, Love"
                        },
                        new
                        {
                            Id = 67,
                            CategoryId = 6,
                            Description = "When their relationship turns sour, a couple undergoes a medical procedure to have each other erased from their memories.",
                            Director = "Michel Gondry",
                            PosterName = "67.png",
                            Price = 9.99m,
                            Title = "Eternal Sunshine of the Spotless Mind"
                        },
                        new
                        {
                            Id = 68,
                            CategoryId = 6,
                            Description = "A musician helps a young singer find fame, even as age and alcoholism send his own career into a downward spiral.",
                            Director = "Bradley Cooper",
                            PosterName = "68.png",
                            Price = 8.99m,
                            Title = "A Star Is Born"
                        },
                        new
                        {
                            Id = 69,
                            CategoryId = 6,
                            Description = "Two teenage cancer patients begin a life-affirming journey to visit a reclusive author in Amsterdam.",
                            Director = "Josh Boone",
                            PosterName = "69.png",
                            Price = 7.99m,
                            Title = "The Fault in Our Stars"
                        },
                        new
                        {
                            Id = 70,
                            CategoryId = 6,
                            Description = "The life of a simple bookshop owner changes when he meets the most famous film star in the world.",
                            Director = "Roger Michell",
                            PosterName = "70.png",
                            Price = 6.99m,
                            Title = "Notting Hill"
                        },
                        new
                        {
                            Id = 71,
                            CategoryId = 6,
                            Description = "Follows the lives of eight very different couples in dealing with their love lives in various loosely interrelated tales all set during a frantic month before Christmas in London, England.",
                            Director = "Richard Curtis",
                            PosterName = "71.png",
                            Price = 5.99m,
                            Title = "Love Actually"
                        },
                        new
                        {
                            Id = 72,
                            CategoryId = 6,
                            Description = "A car accident puts Paige in a coma, and when she wakes up with severe memory loss, her husband Leo works to win her heart again.",
                            Director = "Michael Sucsy",
                            PosterName = "72.png",
                            Price = 4.99m,
                            Title = "The Vow"
                        },
                        new
                        {
                            Id = 73,
                            CategoryId = 7,
                            Description = "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
                            Director = "Quentin Tarantino",
                            PosterName = "73.png",
                            Price = 17.99m,
                            Title = "Pulp Fiction"
                        },
                        new
                        {
                            Id = 74,
                            CategoryId = 7,
                            Description = "Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.",
                            Director = "David Fincher",
                            PosterName = "74.png",
                            Price = 18.99m,
                            Title = "Se7en"
                        },
                        new
                        {
                            Id = 75,
                            CategoryId = 7,
                            Description = "A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer.",
                            Director = "Jonathan Demme",
                            PosterName = "75.png",
                            Price = 19.99m,
                            Title = "The Silence of the Lambs"
                        },
                        new
                        {
                            Id = 76,
                            CategoryId = 7,
                            Description = "With his wife's disappearance having become the focus of an intense media circus, a man sees the spotlight turned on him when it's suspected that he may not be innocent.",
                            Director = "David Fincher",
                            PosterName = "76.png",
                            Price = 20.99m,
                            Title = "Gone Girl"
                        },
                        new
                        {
                            Id = 77,
                            CategoryId = 7,
                            Description = "In 1954, a U.S. Marshal investigates the disappearance of a murderer who escaped from a hospital for the criminally insane.",
                            Director = "Martin Scorsese",
                            PosterName = "77.png",
                            Price = 21.99m,
                            Title = "Shutter Island"
                        },
                        new
                        {
                            Id = 78,
                            CategoryId = 7,
                            Description = "Journalist Mikael Blomkvist is aided in his search for a woman who has been missing for forty years by Lisbeth Salander, a young computer hacker.",
                            Director = "David Fincher",
                            PosterName = "78.png",
                            Price = 22.99m,
                            Title = "The Girl with the Dragon Tattoo"
                        },
                        new
                        {
                            Id = 79,
                            CategoryId = 7,
                            Description = "When Keller Dover's daughter and her friend go missing, he takes matters into his own hands as the police pursue multiple leads and the pressure mounts.",
                            Director = "Denis Villeneuve",
                            PosterName = "79.png",
                            Price = 23.99m,
                            Title = "Prisoners"
                        },
                        new
                        {
                            Id = 80,
                            CategoryId = 7,
                            Description = "In the late 1960s/early 1970s, a San Francisco cartoonist becomes an amateur detective obsessed with tracking down the Zodiac Killer.",
                            Director = "David Fincher",
                            PosterName = "80.png",
                            Price = 24.99m,
                            Title = "Zodiac"
                        },
                        new
                        {
                            Id = 81,
                            CategoryId = 7,
                            Description = "An undercover cop and a mole in the Massachusetts State Police infiltrate an Irish gang in South Boston.",
                            Director = "Martin Scorsese",
                            PosterName = "81.png",
                            Price = 25.99m,
                            Title = "The Departed"
                        },
                        new
                        {
                            Id = 82,
                            CategoryId = 7,
                            Description = "A man with short-term memory loss attempts to track down his wife's murderer.",
                            Director = "Christopher Nolan",
                            PosterName = "82.png",
                            Price = 26.99m,
                            Title = "Memento"
                        },
                        new
                        {
                            Id = 83,
                            CategoryId = 7,
                            Description = "After being kidnapped and imprisoned for fifteen years, Oh Dae-Su is released, only to find that he must find his captor in five days.",
                            Director = "Park Chan-wook",
                            PosterName = "83.png",
                            Price = 27.99m,
                            Title = "Oldboy"
                        },
                        new
                        {
                            Id = 84,
                            CategoryId = 7,
                            Description = "A sole survivor tells of the twisty events leading up to a horrific gun battle on a boat, which began when five criminals met at a seemingly random police lineup.",
                            Director = "Bryan Singer",
                            PosterName = "84.png",
                            Price = 28.99m,
                            Title = "The Usual Suspects"
                        },
                        new
                        {
                            Id = 85,
                            CategoryId = 8,
                            Description = "A cowboy doll is profoundly threatened and jealous when a new spaceman action figure supplants him as top toy in a boy's room.",
                            Director = "John Lasseter",
                            PosterName = "85.png",
                            Price = 12.99m,
                            Title = "Toy Story"
                        },
                        new
                        {
                            Id = 86,
                            CategoryId = 8,
                            Description = "When the newly crowned Queen Elsa accidentally uses her power to turn things into ice to curse her home in infinite winter, her sister Anna teams up with a mountain man, his playful reindeer, and a snowman to change the weather condition.",
                            Director = "Chris Buck",
                            PosterName = "86.png",
                            Price = 13.99m,
                            Title = "Frozen"
                        },
                        new
                        {
                            Id = 87,
                            CategoryId = 8,
                            Description = "A young lion prince is cast out of his pride by his cruel uncle, who claims he killed his father. While the uncle rules with an iron paw, the prince grows up beyond the Savannah, living by a philosophy: No worries for the rest of your days.",
                            Director = "Jon Favreau",
                            PosterName = "87.png",
                            Price = 14.99m,
                            Title = "The Lion King"
                        },
                        new
                        {
                            Id = 88,
                            CategoryId = 8,
                            Description = "After his son is captured in the Great Barrier Reef and taken to Sydney, a timid clownfish sets out on a journey to bring him home.",
                            Director = "Andrew Stanton",
                            PosterName = "88.png",
                            Price = 15.99m,
                            Title = "Finding Nemo"
                        },
                        new
                        {
                            Id = 89,
                            CategoryId = 8,
                            Description = "Seventy-eight year old Carl Fredricksen travels to Paradise Falls in his home equipped with balloons, inadvertently taking a young stowaway.",
                            Director = "Pete Docter",
                            PosterName = "89.png",
                            Price = 16.99m,
                            Title = "Up"
                        },
                        new
                        {
                            Id = 90,
                            CategoryId = 8,
                            Description = "After young Riley is uprooted from her Midwest life and moved to San Francisco, her emotions - Joy, Fear, Anger, Disgust and Sadness - conflict on how best to navigate a new city, house, and school.",
                            Director = "Pete Docter",
                            PosterName = "90.png",
                            Price = 17.99m,
                            Title = "Inside Out"
                        },
                        new
                        {
                            Id = 91,
                            CategoryId = 8,
                            Description = "A mean lord exiles fairytale creatures to the swamp of a grumpy ogre, who must go on a quest and rescue a princess for the lord in order to get his land back.",
                            Director = "Andrew Adamson",
                            PosterName = "91.png",
                            Price = 18.99m,
                            Title = "Shrek"
                        },
                        new
                        {
                            Id = 92,
                            CategoryId = 8,
                            Description = "In a city of anthropomorphic animals, a rookie bunny cop and a cynical con artist fox must work together to uncover a conspiracy.",
                            Director = "Byron Howard",
                            PosterName = "92.png",
                            Price = 19.99m,
                            Title = "Zootopia"
                        },
                        new
                        {
                            Id = 93,
                            CategoryId = 8,
                            Description = "In Ancient Polynesia, when a terrible curse incurred by the Demigod Maui reaches Moana's island, she answers the Ocean's call to seek out the Demigod to set things right.",
                            Director = "Ron Clements",
                            PosterName = "93.png",
                            Price = 20.99m,
                            Title = "Moana"
                        },
                        new
                        {
                            Id = 94,
                            CategoryId = 8,
                            Description = "Aspiring musician Miguel, confronted with his family's ancestral ban on music, enters the Land of the Dead to find his great-great-grandfather, a legendary singer.",
                            Director = "Lee Unkrich",
                            PosterName = "94.png",
                            Price = 21.99m,
                            Title = "Coco"
                        },
                        new
                        {
                            Id = 95,
                            CategoryId = 8,
                            Description = "A family of undercover superheroes, while trying to live the quiet suburban life, are forced into action to save the world.",
                            Director = "Brad Bird",
                            PosterName = "95.png",
                            Price = 22.99m,
                            Title = "The Incredibles"
                        },
                        new
                        {
                            Id = 96,
                            CategoryId = 8,
                            Description = "When a criminal mastermind uses a trio of orphan girls as pawns for a grand scheme, he finds their love is profoundly changing him for the better.",
                            Director = "Pierre Coffin",
                            PosterName = "96.png",
                            Price = 23.99m,
                            Title = "Despicable Me"
                        },
                        new
                        {
                            Id = 97,
                            CategoryId = 9,
                            Description = "A documentary that challenges former Indonesian death-squad leaders to reenact their real-life mass-killings in the style of the American movies they love.",
                            Director = "Joshua Oppenheimer",
                            PosterName = "97.png",
                            Price = 12.99m,
                            Title = "The Act of Killing"
                        },
                        new
                        {
                            Id = 98,
                            CategoryId = 9,
                            Description = "A documentary following the controversial captivity of killer whales, and its dangers for both humans and whales.",
                            Director = "Gabriela Cowperthwaite",
                            PosterName = "98.png",
                            Price = 13.99m,
                            Title = "Blackfish"
                        },
                        new
                        {
                            Id = 99,
                            CategoryId = 9,
                            Description = "A documentary on 85-year-old sushi master Jiro Ono, his renowned Tokyo restaurant, and his relationship with his son and eventual heir, Yoshikazu.",
                            Director = "David Gelb",
                            PosterName = "99.png",
                            Price = 14.99m,
                            Title = "Jiro Dreams of Sushi"
                        },
                        new
                        {
                            Id = 100,
                            CategoryId = 9,
                            Description = "In the Antarctic, every March since the beginning of time, the quest begins to find the perfect mate and start a family.",
                            Director = "Luc Jacquet",
                            PosterName = "100.png",
                            Price = 15.99m,
                            Title = "March of the Penguins"
                        },
                        new
                        {
                            Id = 101,
                            CategoryId = 9,
                            Description = "Filmmaker Davis Guggenheim follows Al Gore on the lecture circuit, as the former presidential candidate campaigns to raise public awareness of the dangers of global warming.",
                            Director = "Davis Guggenheim",
                            PosterName = "101.png",
                            Price = 16.99m,
                            Title = "An Inconvenient Truth"
                        },
                        new
                        {
                            Id = 102,
                            CategoryId = 9,
                            Description = "Charting the rise of Michael Jordan's iconic career, with rare and never-before-seen footage.",
                            Director = "Jason Hehir",
                            PosterName = "102.png",
                            Price = 17.99m,
                            Title = "The Last Dance"
                        },
                        new
                        {
                            Id = 103,
                            CategoryId = 9,
                            Description = "Alex Honnold attempts to become the first person to ever free solo climb El Capitan.",
                            Director = "Elizabeth Chai Vasarhelyi",
                            PosterName = "103.png",
                            Price = 18.99m,
                            Title = "Free Solo"
                        },
                        new
                        {
                            Id = 104,
                            CategoryId = 9,
                            Description = "An exploration of the life, lessons, and legacy of iconic children's television host, Fred Rogers.",
                            Director = "Morgan Neville",
                            PosterName = "104.png",
                            Price = 19.99m,
                            Title = "Won't You Be My Neighbor?"
                        },
                        new
                        {
                            Id = 105,
                            CategoryId = 9,
                            Description = "Using state-of-the-art equipment, a group of activists, led by renowned dolphin trainer Ric O'Barry, infiltrate a cove near Taiji, Japan to expose both a shocking instance of animal abuse and a serious threat to human health.",
                            Director = "Louie Psihoyos",
                            PosterName = "105.png",
                            Price = 20.99m,
                            Title = "The Cove"
                        },
                        new
                        {
                            Id = 106,
                            CategoryId = 9,
                            Description = "A documentarian and a reporter travel to Hong Kong for the first of many meetings with Edward Snowden.",
                            Director = "Laura Poitras",
                            PosterName = "106.png",
                            Price = 21.99m,
                            Title = "Citizenfour"
                        },
                        new
                        {
                            Id = 107,
                            CategoryId = 9,
                            Description = "A look at tightrope walker Philippe Petit's daring, but illegal, high-wire routine performed between New York City's World Trade Center's twin towers in 1974, what some consider the artistic crime of the century.",
                            Director = "James Marsh",
                            PosterName = "107.png",
                            Price = 22.99m,
                            Title = "Man on Wire"
                        },
                        new
                        {
                            Id = 108,
                            CategoryId = 9,
                            Description = "Archival footage and personal testimonies present an intimate portrait of the life and career of British singer-songwriter Amy Winehouse.",
                            Director = "Asif Kapadia",
                            PosterName = "108.png",
                            Price = 23.99m,
                            Title = "Amy"
                        },
                        new
                        {
                            Id = 109,
                            CategoryId = 10,
                            Description = "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.",
                            Director = "Peter Jackson",
                            PosterName = "109.png",
                            Price = 24.99m,
                            Title = "The Lord of the Rings: The Fellowship of the Ring"
                        },
                        new
                        {
                            Id = 110,
                            CategoryId = 10,
                            Description = "An orphaned boy enrolls in a school of wizardry, where he learns the truth about himself, his family and the terrible evil that haunts the magical world.",
                            Director = "Chris Columbus",
                            PosterName = "110.png",
                            Price = 23.99m,
                            Title = "Harry Potter and the Sorcerer's Stone"
                        },
                        new
                        {
                            Id = 111,
                            CategoryId = 10,
                            Description = "In the falangist Spain of 1944, the bookish young stepdaughter of a sadistic army officer escapes into an eerie but captivating fantasy world.",
                            Director = "Guillermo del Toro",
                            PosterName = "111.png",
                            Price = 22.99m,
                            Title = "Pan's Labyrinth"
                        },
                        new
                        {
                            Id = 112,
                            CategoryId = 10,
                            Description = "While home sick in bed, a young boy's grandfather reads him the story of a farmboy-turned-pirate who encounters numerous obstacles, enemies and allies in his quest to be reunited with his true love.",
                            Director = "Rob Reiner",
                            PosterName = "112.png",
                            Price = 21.99m,
                            Title = "The Princess Bride"
                        },
                        new
                        {
                            Id = 113,
                            CategoryId = 10,
                            Description = "In a countryside town bordering on a magical land, a young man makes a promise to his beloved that he'll retrieve a fallen star by venturing into the magical realm.",
                            Director = "Matthew Vaughn",
                            PosterName = "113.png",
                            Price = 20.99m,
                            Title = "Stardust"
                        },
                        new
                        {
                            Id = 114,
                            CategoryId = 10,
                            Description = "Four siblings step through a wardrobe door and into the land of Narnia, a land frozen in eternal winter and enslaved by the power of the White Witch.",
                            Director = "Andrew Adamson",
                            PosterName = "114.png",
                            Price = 19.99m,
                            Title = "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe"
                        },
                        new
                        {
                            Id = 115,
                            CategoryId = 10,
                            Description = "A reluctant dwarf must play a critical role in protecting a special baby from an evil queen.",
                            Director = "Ron Howard",
                            PosterName = "115.png",
                            Price = 18.99m,
                            Title = "Willow"
                        },
                        new
                        {
                            Id = 116,
                            CategoryId = 10,
                            Description = "A troubled boy dives into a wondrous fantasy world through the pages of a mysterious book.",
                            Director = "Wolfgang Petersen",
                            PosterName = "116.png",
                            Price = 17.99m,
                            Title = "The NeverEnding Story"
                        },
                        new
                        {
                            Id = 117,
                            CategoryId = 10,
                            Description = "A young man must stop the Lord of Darkness from both destroying daylight and marrying the woman he loves.",
                            Director = "Ridley Scott",
                            PosterName = "117.png",
                            Price = 16.99m,
                            Title = "Legend"
                        },
                        new
                        {
                            Id = 118,
                            CategoryId = 10,
                            Description = "On another planet in the distant past, a Gelfling embarks on a quest to find the missing shard of a magical crystal, and so restore order to his world.",
                            Director = "Jim Henson",
                            PosterName = "118.png",
                            Price = 15.99m,
                            Title = "The Dark Crystal"
                        },
                        new
                        {
                            Id = 119,
                            CategoryId = 10,
                            Description = "Sixteen-year-old Sarah is given thirteen hours to solve a labyrinth and rescue her baby brother Toby when her wish for him to be taken away is granted by the Goblin King.",
                            Director = "Jim Henson",
                            PosterName = "119.png",
                            Price = 14.99m,
                            Title = "Labyrinth"
                        },
                        new
                        {
                            Id = 120,
                            CategoryId = 10,
                            Description = "Upon moving into the run-down Spiderwick Estate with their mother, twin brothers Jared and Simon Grace, along with their sister Mallory, find themselves pulled into an alternate world full of faeries and other creatures.",
                            Director = "Mark Waters",
                            PosterName = "120.png",
                            Price = 13.99m,
                            Title = "The Spiderwick Chronicles"
                        });
                });

            modelBuilder.Entity("mgr_1_2_TI.Models.Movie", b =>
                {
                    b.HasOne("mgr_1_2_TI.Models.Category", "Category")
                        .WithMany("Movies")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("mgr_1_2_TI.Models.Category", b =>
                {
                    b.Navigation("Movies");
                });
#pragma warning restore 612, 618
        }
    }
}
